-- Users table (root entity)
CREATE TABLE Users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    email VARCHAR2(100) UNIQUE NOT NULL,
    phone VARCHAR2(20),
    address VARCHAR2(255)
);

-- WaterMeters table (linked to Users)
CREATE TABLE WaterMeters (
    user_id NUMBER NOT NULL,
    meter_number VARCHAR2(50) PRIMARY KEY,
    location VARCHAR2(255),
    installation_date DATE,
    status VARCHAR2(20) DEFAULT 'active',
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- WaterSources table (linked to Users as owner/manager)
CREATE TABLE WaterSources (
    user_id NUMBER NOT NULL,
    type VARCHAR2(50) NOT NULL,
    location VARCHAR2(255),
    capacity NUMBER(15,2),
    PRIMARY KEY (user_id, type, location),
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- ConsumptionRecords table (linked to Users + WaterMeters)
CREATE TABLE ConsumptionRecords (
    user_id NUMBER NOT NULL,
    water_meter_number VARCHAR2(50) NOT NULL,
    consumption NUMBER(10,2) NOT NULL,
    consumption_date DATE NOT NULL,
    PRIMARY KEY (user_id, water_meter_number, consumption_date),
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (water_meter_number) REFERENCES WaterMeters(meter_number) ON DELETE CASCADE
);

-- Billing table (linked to Users)
CREATE TABLE Billing (
    user_id NUMBER NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_usage NUMBER(10,2) NOT NULL,
    amount_due NUMBER(10,2) NOT NULL,
    payment_status VARCHAR2(20) DEFAULT 'unpaid',
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, period_start, period_end),
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
);

-- ConservationMethod table (global methods)
CREATE TABLE ConservationMethod (
    method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500),
    cost NUMBER(10,2) NOT NULL,
    efficiency_rating NUMBER(1) NOT NULL CHECK (efficiency_rating BETWEEN 1 AND 5),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ImplementationRecord table (linked to Users + ConservationMethod)
CREATE TABLE ImplementationRecord (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    method_id NUMBER NOT NULL,
    date_implemented DATE NOT NULL,
    status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
    savings_achieved NUMBER(10,2),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (method_id) REFERENCES ConservationMethod(method_id) ON DELETE CASCADE
);

-- WaterSavings table (linked to Users, WaterMeters, ImplementationRecord)
CREATE TABLE WaterSavings (
    savings_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    water_meter_number VARCHAR2(50) NOT NULL,
    implementation_id NUMBER NOT NULL,
    savings NUMBER(10,2) NOT NULL,  -- water saved in liters or gallons
    end_date DATE NOT NULL,  -- entered by user
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (water_meter_number) REFERENCES WaterMeters(meter_number) ON DELETE CASCADE,
    FOREIGN KEY (implementation_id) REFERENCES ImplementationRecord(record_id) ON DELETE CASCADE
);
