/**
 * Database Migration Script
 * Runs SQL migrations to create ConservationMethod and ImplementationRecord tables
 */

const { getConnection } = require('./db');

// Migration 1: Create ConservationMethod table
const createConservationMethodTable = async () => {
  const connection = await getConnection();
  try {
    const query = `
      CREATE TABLE ConservationMethod (
        method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        method_name VARCHAR2(100) NOT NULL UNIQUE,
        description VARCHAR2(500),
        cost NUMBER(10,2) NOT NULL,
        efficiency_rating NUMBER(1) NOT NULL CHECK (efficiency_rating BETWEEN 1 AND 5),
        date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      )
    `;
    
    await connection.execute(query, {}, { autoCommit: true });
    console.log('✓ ConservationMethod table created successfully');
  } catch (err) {
    if (err.message.includes('ORA-00955') || err.message.includes('already exists')) {
      console.log('✓ ConservationMethod table already exists');
    } else {
      throw err;
    }
  } finally {
    await connection.close();
  }
};

// Migration 2: Create ImplementationRecord table
const createImplementationRecordTable = async () => {
  const connection = await getConnection();
  try {
    const query = `
      CREATE TABLE ImplementationRecord (
        record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL,
        method_id NUMBER NOT NULL,
        date_implemented DATE NOT NULL,
        status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')),
        savings_achieved NUMBER(10,2),
        date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
        FOREIGN KEY (method_id) REFERENCES ConservationMethod(method_id) ON DELETE CASCADE
      )
    `;
    
    await connection.execute(query, {}, { autoCommit: true });
    console.log('✓ ImplementationRecord table created successfully');
  } catch (err) {
    if (err.message.includes('ORA-00955') || err.message.includes('already exists')) {
      console.log('✓ ImplementationRecord table already exists');
    } else {
      throw err;
    }
  } finally {
    await connection.close();
  }
};

// Migration 3: Insert sample conservation methods
const insertSampleMethods = async () => {
  const connection = await getConnection();
  try {
    const methods = [
      { name: 'Rainwater Harvesting', desc: 'Collect and store rainwater for garden and outdoor use', cost: 500, rating: 4 },
      { name: 'Drip Irrigation', desc: 'Install drip irrigation system to reduce water waste in gardens', cost: 300, rating: 5 },
      { name: 'Water-Efficient Toilets', desc: 'Replace traditional toilets with dual-flush or low-flow models', cost: 400, rating: 4 },
      { name: 'Recycling Greywater', desc: 'Recycle water from showers, sinks, and washing machines', cost: 600, rating: 3 },
      { name: 'Smart Water Meter', desc: 'Install smart meter to monitor real-time water consumption', cost: 200, rating: 5 },
      { name: 'Low-Flow Showerheads', desc: 'Install showerheads that reduce water flow without affecting pressure', cost: 50, rating: 4 },
      { name: 'Mulching', desc: 'Apply mulch around plants to retain soil moisture', cost: 100, rating: 3 },
      { name: 'Native Plant Garden', desc: 'Plant drought-resistant native species that require less water', cost: 200, rating: 4 }
    ];

    let inserted = 0;

    for (const method of methods) {
      try {
        const query = `
          INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
          VALUES (:name, :desc, :cost, :rating)
        `;

        await connection.execute(query, 
          { 
            name: method.name, 
            desc: method.desc, 
            cost: method.cost, 
            rating: method.rating 
          },
          { autoCommit: true }
        );
        console.log(`  ✓ ${method.name}`);
        inserted++;
      } catch (err) {
        if (err.message.includes('ORA-00001') || err.message.includes('unique constraint')) {
          console.log(`  • ${method.name} (already exists)`);
        } else {
          console.error(`  ✗ Error inserting ${method.name}:`, err.message);
        }
      }
    }

    console.log(`✓ Sample conservation methods ready (${inserted} new, ${methods.length - inserted} existing)`);
  } finally {
    await connection.close();
  }
};

// Run all migrations
const runMigrations = async () => {
  console.log('\n📦 Running Database Migrations...\n');
  
  try {
    console.log('1. Creating ConservationMethod table...');
    await createConservationMethodTable();

    console.log('\n2. Creating ImplementationRecord table...');
    await createImplementationRecordTable();

    console.log('\n3. Inserting sample conservation methods...');
    await insertSampleMethods();

    console.log('\n✅ All migrations completed successfully!\n');
    process.exit(0);
  } catch (error) {
    console.error('\n❌ Migration failed:', error.message);
    console.error(error);
    process.exit(1);
  }
};

// Run if called directly
if (require.main === module) {
  runMigrations();
}

module.exports = { runMigrations, createConservationMethodTable, createImplementationRecordTable, insertSampleMethods };
