-- Migration: Add ConservationMethod and ImplementationRecord tables
-- Date: November 26, 2025

-- ConservationMethod table (global methods)
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE ConservationMethod (
    method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    method_name VARCHAR2(100) NOT NULL UNIQUE,
    description VARCHAR2(500),
    cost NUMBER(10,2) NOT NULL,
    efficiency_rating NUMBER(1) NOT NULL CHECK (efficiency_rating BETWEEN 1 AND 5),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  )';
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ConservationMethod table created successfully');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('ConservationMethod table already exists');
    ELSE
      RAISE;
    END IF;
END;
/

-- ImplementationRecord table (linked to Users + ConservationMethod)
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE ImplementationRecord (
    record_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    method_id NUMBER NOT NULL,
    date_implemented DATE NOT NULL,
    status VARCHAR2(20) DEFAULT ''active'' CHECK (status IN (''active'', ''inactive'')),
    savings_achieved NUMBER(10,2),
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (method_id) REFERENCES ConservationMethod(method_id) ON DELETE CASCADE
  )';
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('ImplementationRecord table created successfully');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('ImplementationRecord table already exists');
    ELSE
      RAISE;
    END IF;
END;
/

-- Create indexes for better query performance
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_conservation_method_name ON ConservationMethod(method_name)';
  DBMS_OUTPUT.PUT_LINE('Index on method_name created');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1408 THEN
      DBMS_OUTPUT.PUT_LINE('Index already exists');
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_implementation_user_id ON ImplementationRecord(user_id)';
  DBMS_OUTPUT.PUT_LINE('Index on user_id created');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1408 THEN
      DBMS_OUTPUT.PUT_LINE('Index already exists');
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_implementation_method_id ON ImplementationRecord(method_id)';
  DBMS_OUTPUT.PUT_LINE('Index on method_id created');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1408 THEN
      DBMS_OUTPUT.PUT_LINE('Index already exists');
    ELSE
      RAISE;
    END IF;
END;
/

-- Insert sample conservation methods
BEGIN
  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Rainwater Harvesting', 'Collect and store rainwater for garden and outdoor use', 500, 4);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Drip Irrigation', 'Install drip irrigation system to reduce water waste in gardens', 300, 5);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Water-Efficient Toilets', 'Replace traditional toilets with dual-flush or low-flow models', 400, 4);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Recycling Greywater', 'Recycle water from showers, sinks, and washing machines', 600, 3);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Smart Water Meter', 'Install smart meter to monitor real-time water consumption', 200, 5);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Low-Flow Showerheads', 'Install showerheads that reduce water flow without affecting pressure', 50, 4);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Mulching', 'Apply mulch around plants to retain soil moisture', 100, 3);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Native Plant Garden', 'Plant drought-resistant native species that require less water', 200, 4);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Rainwater harvesting systems on rooftops and public buildings', 'Systems designed to collect and store rainwater from rooftops and public buildings', 700, 4);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Groundwater recharge through percolation pits and recharge wells', 'Techniques to increase groundwater levels via percolation pits and recharge wells', 400, 5);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Wastewater recycling for industrial and landscaping use', 'Recycle treated wastewater for use in industrial processes and landscape irrigation', 800, 4);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Watershed management to protect forests, wetlands, and catchment areas', 'Manage watersheds to preserve forests, wetlands, and catchment areas for water sustainability', 600, 5);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Build check dams and bunds to store rainwater', 'N/A', 0, 3);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Rainwater harvesting systems on rooftops and public buildings', 'N/A', 0, 3);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Groundwater recharge through percolation pits and recharge wells', 'N/A', 0, 3);

  INSERT INTO ConservationMethod (method_name, description, cost, efficiency_rating)
  VALUES ('Wastewater recycling for industrial and landscaping use', 'N/A', 0, 3);

  COMMIT;
  DBMS_OUTPUT.PUT_LINE('Sample conservation methods inserted successfully');

COMMIT;
