-- Migration: Add WaterSavings table
-- Date: [Current Date]

BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE WaterSavings (
    savings_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    water_meter_number VARCHAR2(50) NOT NULL,
    implementation_id NUMBER NOT NULL,
    end_date DATE NOT NULL,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
    FOREIGN KEY (implementation_id) REFERENCES ImplementationRecord(record_id) ON DELETE CASCADE
  )';
  COMMIT;
  DBMS_OUTPUT.PUT_LINE('WaterSavings table created successfully');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -955 THEN
      DBMS_OUTPUT.PUT_LINE('WaterSavings table already exists');
    ELSE
      RAISE;
    END IF;
END;
/

-- Create indexes for better query performance
BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_water_savings_user_id ON WaterSavings(user_id)';
  DBMS_OUTPUT.PUT_LINE('Index on user_id created');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1408 THEN
      DBMS_OUTPUT.PUT_LINE('Index already exists');
    ELSE
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_water_savings_implementation_id ON WaterSavings(implementation_id)';
  DBMS_OUTPUT.PUT_LINE('Index on implementation_id created');
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -1408 THEN
      DBMS_OUTPUT.PUT_LINE('Index already exists');
    ELSE
      RAISE;
    END IF;
END;
/

COMMIT;
